name: geosocial
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^0.6.9
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  freezed_annotation: ^0.12.0

  pedantic: ^1.9.2
  json_serializable: ^3.5.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  get_it: ^5.0.6
  injectable: ^1.0.7

  dio: ^3.0.10
  gql_dio_link: ^0.0.4
  pretty_dio_logger: ^1.1.1
  url_launcher: ^6.0.3
  shimmer: ^1.1.2
  vibration: ^1.7.3
  connectivity: ^3.0.3 
  # UI
  google_fonts: any
  font_awesome_flutter: ^9.0.0
  dartz: ^0.9.2

  # graphql_flutter: ^4.0.0
  graphql: ^4.0.1

  google_maps_flutter: ^2.0.1

  geolocator: ^7.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1,11,1
  freezed: ^0.12.7
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.0.7
  hive_generator: ^0.8.2
  artemis: ^6.18.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
scripts: derry.yaml
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #  - google_fonts/
    - assets/icons/
    - assets/images/
    - assets/images/stars/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/CustomIcons.ttf

analyzer:
  exclude:
    - "*/**/*.g.dart"
    - "*/**/*.freezed.dart"
